baseURL = "https://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-profile" 
[params]
  title = "Drisanth"
  description = "A passionate full stack web developer from India 🇮🇳"
  favicon = "images/favicon.ico"
  avatar = "images/avatar.png"
  cover = "images/cover.png"
  resume = "files/resume.pdf"
  contactForm = true

  [params.profileMode]
    enabled = true
    title = "Hi, I'm Drisanth 👋"
    subtitle = "I love building web apps that solve real-world problems."
    imageUrl = "images/avatar.png"
    imageTitle = "My photo"
    imageWidth = 120
    imageHeight = 120

  [[params.socials]]
    name = "Github"
    icon = "fa-brands fa-github"
    url = "https://github.com/yourusername"

  [[params.socials]]
    name = "LinkedIn"
    icon = "fa-brands fa-linkedin"
    url = "https://linkedin.com/in/yourusername"

  [[params.socials]]
    name = "Email"
    icon = "fa-solid fa-envelope"
    url = "mailto:you@example.com"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "#about"
    weight = 1

  [[menu.main]]
    identifier = "skills"
    name = "Skills"
    url = "#skills"
    weight = 2

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "#projects"
    weight = 3

  [[menu.main]]
    identifier = "experience"
    name = "Experience"
    url = "#experience"
    weight = 4

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "#contact"
    weight = 5
