name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master' if you're using that

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # if using themes as submodules

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.121.1'

      - name: Build
        run: hugo --minify --baseURL "https://drisanth.github.io/drisanth/"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
